name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up the Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install the dependencies
        run: npm install

      - name: Run the linter
        run: npm run lint
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up the Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install the dependencies
        run: npm install

      - name: Run the formatter
        run: npm run format-check
  test-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up the Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install the dependencies
        run: npm install

      - name: Run the tests
        run: npm run test ./
